version: '3.8'

services:
  apache:
    image: httpd:2.4
    container_name: apache
    ports:
      - "80:80"
    volumes:
      - ./apache-config:/usr/local/apache2/conf
      - ./www:/usr/local/apache2/htdocs
    networks:
      webnet:
        ipv4_address: 192.168.1.10

  dns:
    image: andyshinn/dnsmasq:2.85
    container_name: dns
    ports:
      - "53:53/udp"
    environment:
      - DNSMASQ_USER=root
    volumes:
      - ./dnsmasq.conf:/etc/dnsmasq.conf
    networks:
      webnet:
        ipv4_address: 192.168.1.11

networks:
  webnet:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.1.0/24
